#!/bin/sh

umask 022

target=$HOME/bin/`uname -p`
source=`which ccache`
compilers="
cc
CC
c++
g++
g++-2.95
g++-3.0
g++-3.2
g++-3.3
g++-3.4
g++-4.0
g++-4.1
gcc
gcc-2.95
gcc-3.0
gcc-3.2
gcc-3.3
gcc-3.4
gcc-4.0
gcc-4.1
i486-linux-gnu-g++
i486-linux-gnu-g++-2.95
i486-linux-gnu-g++-3.0
i486-linux-gnu-g++-3.2
i486-linux-gnu-g++-3.3
i486-linux-gnu-g++-3.4
i486-linux-gnu-g++-4.0
i486-linux-gnu-g++-4.1
i486-linux-gnu-gcc
i486-linux-gnu-gcc-2.95
i486-linux-gnu-gcc-3.0
i486-linux-gnu-gcc-3.2
i486-linux-gnu-gcc-3.3
i486-linux-gnu-gcc-3.4
i486-linux-gnu-gcc-4.0
i486-linux-gnu-gcc-4.1
"

if [ ! -d $target ]; then
	mkdir -p $target
fi

cd $target
for i in $compilers
do
    rm -f $i
    echo "link $source to $i"
    ln -s $source $i
done
